name: sensors_plus
description: Flutter plugin for accessing accelerometer, gyroscope,
  magnetometer, and heartrate sensors.
version: 5.0.2
publish_to: none

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.sensors
        pluginClass: SensorsPlugin
      ios:
        pluginClass: FPPSensorsPlusPlugin
      web:
        pluginClass: WebSensorsPlugin
        fileName: src/sensors_plus_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  sensors_plus_platform_interface: 
    git:
      url: https://github.com/adechant/plus_plugins
      path: packages/sensors_plus/sensors_plus_platform_interface
dev_dependencies:
  test: ^1.22.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.1 <4.0.0"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
